### ISSUE TITLE
Escape character

### ISSUE THREAD

**Issue by v4ltages** [cnrad/next-template#3]
You should switch the ' character to either `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.
This will cause deployment issues for users if they were to make a repo with the template while also using a deployment service like Vercel.

``
Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
``

**Comment by cnrad** [comment]
Done, thanks
